apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 			# Only required field
      targetPort: 80    # Same as port if not specified
      nodePort: 30008   # Free port in range would be allocated if not specified
  selector:
    app: myapp
    type: front-end
