apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - port: 80 			# Only required field
      targetPort: 80    # Same as port if not specified
  selector:
    app: myapp
    type: back-end
